apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  labels:
    app: go-api
data:
  # Add any configuration files from your config directory
  app.env: |
    APP_ENV=production
    PORT=8080
    SERVER_READ_TIMEOUT=10s
    SERVER_WRITE_TIMEOUT=10s
    SERVER_SHUTDOWN_TIMEOUT=10s
    LOG_LEVEL=info
    LOG_FORMAT=json
    LOG_OUTPUT_PATH=stdout
    REDIS_ENABLED=true
    REDIS_HOST=redis
    REDIS_PORT=6380
    REDIS_DB=0
    REDIS_CACHE_TTL=15m
    REDIS_QUERY_CACHING=true
    REDIS_KEY_PREFIX=linkeun_api:
    REDIS_POOL_SIZE=10
