apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secrets.yaml
  - mysql.yaml
  - redis.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: go-api
  app.kubernetes.io/instance: dev
